### ISSUE TITLE
Feature request: sorting search results

### ISSUE THREAD

**Issue by attam** [TeamNewPipe/documentation#17] opened 2020-03-08 18:00 UTC
Firstly, great work! I just started using the android app and appreciate your efforts.
In searching, I noticed there is a lack of sorting and filtering function for the results, which would be helpful. E.g., sort by views, duration, date, etc. If anyone is willing to implement, consider bidirectional sort (eg, date: oldest/newest first, longest/shortest first).
Filter examples: before/after date x/custom date range; duration longer or shorter than x minutes; more than x views.
![Screenshot_20200308-125028](https://user-images.githubusercontent.com/32426130/76168308-9d1bd380-613c-11ea-9c29-e9a7cbf46925.png)

**Comment by B0pol** [comment] 2020-04-19 14:26
This is not the right repository.
And it's a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/110
@TobiGr please close this.

**Closed** 2020-05-03 19:35 UTC
